name = "OCGOSS Aeronautics"
author = "MangoCat54"
version = "1.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19d3954044caafbed55d64bbf5fedf93907126d8a9d0599e91189b2e816b2314"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
